import { LegalPage, Section } from "@/components/legal-page";

export const metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="2026-04-21">
      <Section heading="Service">
        <p>
          Vantage provides curated Valorant learning content and AI-powered
          match analysis. The service is educational in nature and offers no
          guarantee of in-game performance or rank improvement.
        </p>
      </Section>
      <Section heading="Eligibility">
        <p>
          You must be at least the minimum age required by the data protection
          laws of your country (typically 16 in the EU and 13+ elsewhere,
          subject to local law) and comply with the Riot Games Terms of
          Service.
        </p>
      </Section>
      <Section heading="Account">
        <p>
          You are responsible for keeping your credentials confidential. You
          may delete your account at any time; a 30-day soft-delete window
          applies before permanent deletion.
        </p>
      </Section>
      <Section heading="Acceptable use">
        <ul className="list-disc pl-5 flex flex-col gap-1">
          <li>No automated scraping or abuse of the service.</li>
          <li>No attempts to bypass usage quotas or security controls.</li>
          <li>No sharing of accounts or redistribution of paid features.</li>
        </ul>
      </Section>
      <Section heading="Payments">
        <p>
          Paid subscriptions are processed by Paddle as Merchant of Record.
          See the Refunds page for withdrawal rights.
        </p>
      </Section>
      <Section heading="Disclaimers">
        <p>
          AI outputs are generated by large language models and may contain
          errors. Vantage is not endorsed by Riot Games. The service is
          provided &quot;as is&quot; without warranties of any kind.
        </p>
      </Section>
      <Section heading="Governing law">
        <p>
          These terms are governed by the laws of Switzerland. Mandatory
          consumer protection rights in your country of residence remain
          unaffected.
        </p>
      </Section>
      <Section heading="Finalization">
        <p>
          These terms are preliminary and will be finalized with legal review
          before public launch.
        </p>
      </Section>
    </LegalPage>
  );
}
